INSERT INTO boisson (nom_boisson, prix_boisson) 
VALUES ('Orangina', '3'),
	   ('Coca Cola','3'),
	   ('Oasis', '3'),
	   ('Ice Tea', '3'),
	   ('Bouteille Chateau-Belle-Vue', '8'),
	   ('Bouteille Chateau-Brown', '9'),
	   ('Bouteille rose Gruet', '7'),
	   ('Whiskey BushMills', '9'),
	   ('Whiskey TullMore Dew', '10');


INSERT INTO personnel (nom_personnel, prenom_personnel, metier_personnel, type_personnel)
VALUES ('Blousot', 'Eric', 'Maitre hotel', 'salle'),
	   ('Portman', 'Nathalie', 'Chef de rang', 'salle'),
	   ('Cage', 'Nicolas', 'Chef de rang', 'salle'),
	   ('Marceau', 'Sophie', 'Serveur', 'salle'),
	   ('Hanks', 'Tom', 'Serveur', 'salle'),
	   ('Willis', 'Bruce', 'Serveur', 'salle'),
	   ('Di Caprio', 'Leonardo', 'Serveur', 'salle'),
	   ('Spacey', 'Kevin', 'Commis de salle', 'salle'),
	   ('Eastwood', 'Clint', 'Chef de cuisine', 'cuisine'),
	   ('Freeman', 'Morgan', 'Chef de partie', 'cuisine'),
	   ('Depp', 'Johnny', 'Chef de partie', 'cuisine'),
	   ('Crowe', 'Russel', 'Commis de cuisine', 'cuisine'),
	   ('Pitt', 'Brad', 'Commis de cuisine', 'cuisine'),
	   ('Pinyan', 'Kenneth', 'Plongeur', 'cuisine');


INSERT INTO recette (nom_recette, prix_recette, type_recette, preparateur_recette, stockage_recette, temps_preparation, temps_repos, temps_cuisson)
VALUES ('Flan Parisien', '5', 'dessert', 'Morgan Freeman', 'frigo', '00:15:00', '00:40:00', '00:35:00'),
	   ('Crumble Cerise et Miel', '5', 'dessert', 'Johnny Depp', 'frigo', '00:20:00', '01:00:00', '00:30:00'),
	   ('Carpaccio de vieille mangue et citron vert', '17', 'plat', 'Morgan Freeman', 'reserve', '00:35:00', '00:00:00', '00:00:00'),
	   ('Gigue de chevreuil marine', '17', 'plat', 'Johnny Depp', 'reserve', '00:30:00', '00:45:00', '00:10:00'),
	   ('Tatin de magret de canard au foie gras', '9', 'entree', 'Morgan Freeman', 'frigo', '00:15:00', '00:00:00', '00:10:00'),
	   ('Tarte poireaux et lardons', '9', 'entree', 'Johnny Depp', 'reserve', '00:25:00', '00:20:00', '00:25:00');


INSERT INTO ingredient (nom_ingredient, stockage_ingredient)
VALUES ('Pate brisee', 'frigo'),
	   ('Maizena', 'reserve'),
	   ('Sucre', 'reserve'),
	   ('Sachet sucre vanille', 'reserve'),
	   ('Oeuf', 'frigo'),
	   ('Lait', 'frigo'),
	   ('Cerise noire', 'reserve'),
	   ('Miel', 'reserve'),
	   ('Beurre demi sel', 'frigo'),
	   ('Farine', 'reserve'),
	   ('Sucre roux', 'reserve'),
	   ('Poisson vieille', 'congelateur'),
	   ('Citron vert', 'reserve'),
	   ('Mangue', 'reserve'),
	   ('Huile olive', 'reserve'),
	   ('Sel', 'reserve'),
	   ('Poivre', 'reserve'),
	   ('Gigue de chevreuil', 'congelateur'),
	   ('Vinaigre de vin', 'reserve'),
	   ('Vin blanc', 'frigo'),
	   ('Persil', 'reserve'),
	   ('Oignon', 'reserve'),
	   ('Carotte', 'reserve'),
	   ('Creme fraiche', 'frigo'),
	   ('Pomme', 'reserve'),
	   ('Magret de cannard fume', 'congelateur'),
	   ('Pain de mie', 'reserve'),
	   ('Foie gras', 'frigo'),
	   ('Alcool de pomme', 'frigo'),
	   ('Poireau', 'reserve'),
	   ('Lardon', 'frigo'),
	   ('Fromage rape', 'frigo');


INSERT INTO materiel (nom_materiel, nombre_materiel, type_materiel, lavable)
VALUES ('Assiette plate', '150', 'commun', 1),
	   ('Assiette entree', '150', 'commun', 1),
	   ('Assiette creuse', '30', 'commun', 1),
	   ('Assiette dessert', '150', 'commun', 1),
	   ('fourchette', '150', 'commun', 1),
	   ('couteau', '150', 'commun', 1),
	   ('cuillere soupe', '150', 'commun', 1),
	   ('cuillere cafe', '150', 'commun', 1),
	   ('verre a eau', '150', 'commun', 1),
	   ('verre a champagne', '150', 'commun', 1),
	   ('verre a vin', '150', 'commun', 1),
	   ('tasse cafe', '50', 'commun', 1),
	   ('assiette cafe', '50', 'commun', 1),
	   ('serviette', '150', 'commun', 0),
	   ('nappe', '40', 'commun', 0),
	   ('table', '32', 'salle', 0),
	   ('chaise', '', 'salle', 0),
	   ('bouteille eau', '', 'salle', 1),
	   ('corbeille a pain', '', 'salle', 0),
	   ('carte', '40', 'salle', 0),
	   ('feu de cuisine', '5', 'cuisine', 0),
	   ('casserole', '10', 'cuisine', 1),
	   ('poeles', '10', 'cuisine', 1),
	   ('four', '1', 'cuisine', 0),
	   ('cuillere bois', '10', 'cuisine', 1),
	   ('mixeur', '1', 'cuisine', 1),
	   ('bol salade', '5', 'cuisine', 1),
	   ('autocuiseur', '2', 'cuisine', 1),
	   ('presse-agrumes', '1', 'cuisine', 1),
	   ('tamis', '1', 'cuisine', 1),
	   ('entonoir', '1', 'cuisine', 1),
	   ('couteau de cuisine', '5', 'cuisine', 1),
	   ('frigo de travail', '1', 'cuisine', 0),
	   ('lave-vaisselle', '1', 'cuisine', 0),
	   ('machine a laver', '1', 'cuisine', 0),
	   ('evier', '1', 'cuisine', 0);

INSERT INTO tablee (carre_tablee, rang_tablee, capacite_tablee, numero_tablee)
VALUES ('1', '1', '1', '10'),
	   ('1', '1', '2', '10'),
	   ('1', '2', '3', '4'),
	   ('1', '2', '4', '4'),
	   ('1', '2', '5', '4'),
	   ('1', '2', '6', '4'),
	   ('1', '2', '7', '4'),
	   ('1', '2', '8', '4'),
	   ('1', '2', '9', '4'),
	   ('1', '2', '10', '4'),
	   ('1', '2', '11', '4'),
	   ('1', '2', '12', '4'),
	   ('1', '3', '13', '2'),
	   ('1', '3', '14', '2'),
	   ('1', '3', '15', '2'),
	   ('1', '3', '16', '2'),
	   ('1', '3', '17', '2'),
	   ('1', '3', '18', '2'),
	   ('1', '3', '19', '2'),
	   ('1', '3', '20', '2'),
	   ('1', '3', '21', '2'),
	   ('1', '3', '22', '2'),
	   ('2', '4', '23', '8'),
	   ('2', '4', '24', '8'),
	   ('2', '4', '25', '8'),
	   ('2', '4', '26', '8'),
	   ('2', '4', '27', '8'),
	   ('2', '5', '28', '6'),
	   ('2', '5', '29', '6'),
	   ('2', '5', '30', '6'),
	   ('2', '5', '31', '6'),
	   ('2', '5', '32', '6');


