//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterChef3
{
    using System;
    using System.Collections.Generic;
    
    public partial class boisson
    {
        public int id_boisson { get; set; }
        public string nom_boisson { get; set; }
        public decimal prix_boisson { get; set; }
    }
}
