//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterChef3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Masterchef3_Entities : DbContext
    {
        public Masterchef3_Entities()
            : base("name=Masterchef3_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<boisson> boisson { get; set; }
        public virtual DbSet<commande> commande { get; set; }
        public virtual DbSet<commander> commander { get; set; }
        public virtual DbSet<composer> composer { get; set; }
        public virtual DbSet<constituer> constituer { get; set; }
        public virtual DbSet<etre> etre { get; set; }
        public virtual DbSet<ingredient> ingredient { get; set; }
        public virtual DbSet<materiel> materiel { get; set; }
        public virtual DbSet<materiel_lavable> materiel_lavable { get; set; }
        public virtual DbSet<mobiliser> mobiliser { get; set; }
        public virtual DbSet<necessiter> necessiter { get; set; }
        public virtual DbSet<personnel> personnel { get; set; }
        public virtual DbSet<preparer> preparer { get; set; }
        public virtual DbSet<recette> recette { get; set; }
        public virtual DbSet<reservation> reservation { get; set; }
        public virtual DbSet<tablee> tablee { get; set; }
    }
}
