//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterChef3
{
    using System;
    using System.Collections.Generic;
    
    public partial class personnel
    {
        public int id_personnel { get; set; }
        public string nom_personnel { get; set; }
        public string prenom_personnel { get; set; }
        public string metier_personnel { get; set; }
        public string type_personnel { get; set; }
    }
}
