//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterChef3
{
    using System;
    using System.Collections.Generic;
    
    public partial class tablee
    {
        public int id_tablee { get; set; }
        public decimal carre_tablee { get; set; }
        public decimal rang_tablee { get; set; }
        public decimal numero_tablee { get; set; }
        public decimal capacite_tablee { get; set; }
        public short occupation_tablee { get; set; }
    }
}
